wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
  grid:
    columns: [40, 40]
    rows: [13, 13, 4]
  refreshInterval: 1
  mods:
    hackernews:
      enabled: true
      numberOfStories: 10
      position:
        top: 0
        left: 1
        height: 1
        width: 3
      storytype: top
      refreshInterval: 900
    todo:
      enabled: true
      checkedIcon: ""
      filename: "todo.yml"
      position:
        top: 0
        left: 0
        height: 4
        width: 1
      refreshInterval: 3600
      colors:
        checked: gray
    resourceusage:
      enabled: true
      position:
        top: 1
        left: 1
        width: 1
        height: 1
      refreshInterval: 1
